"""The schema against a real Postgres.

These assert the things docs/design.md claims the *database* guarantees. Each one corresponds to a
design decision that would otherwise silently become application logic.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncEngine

from carpool_api.models import ParticipantRole

ARRIVAL = datetime(2026, 9, 20, 16, 0, tzinfo=UTC)


async def _insert_event(engine: AsyncEngine, **overrides: object) -> uuid.UUID:
    event_id = uuid.uuid4()
    values: dict[str, object] = {
        "id": event_id,
        "public_id": uuid.uuid4().hex[:10],
        "name": "Tuesday practice",
        "destination_address": "500 E Liberty St, Ann Arbor, MI",
        "arrival_at": ARRIVAL,
        "ends_at": ARRIVAL + timedelta(hours=2),
        "timezone": "America/Detroit",
        "status": "open",
    }
    values.update(overrides)
    async with engine.begin() as conn:
        await conn.execute(
            text(
                "insert into events (id, public_id, name, destination_address, destination_geog,"
                " arrival_at, ends_at, timezone, status)"
                " values (:id, :public_id, :name, :destination_address,"
                " ST_GeogFromText('SRID=4326;POINT(-83.7430 42.2808)'),"
                " :arrival_at, :ends_at, :timezone, cast(:status as event_status))"
            ),
            values,
        )
    return event_id


async def _insert_job(engine: AsyncEngine, event_id: uuid.UUID, status: str) -> None:
    async with engine.begin() as conn:
        await conn.execute(
            text(
                "insert into optimization_jobs"
                " (id, event_id, status, algorithm, params, input_fingerprint, input_version)"
                " values (:id, :event_id, cast(:status as job_status), 'greedy', '{}'::jsonb,"
                " '\\x00'::bytea, 0)"
            ),
            {"id": uuid.uuid4(), "event_id": event_id, "status": status},
        )


def test_migrations_and_models_agree(migrated_url: str, alembic_ini: Path) -> None:
    """The drift guard.

    Models are the source of truth and migrations are generated from them, so the two can silently
    diverge the moment someone edits a model without generating a migration. `alembic check` runs
    autogenerate against the migrated database and fails if it would emit anything.

    Deliberately synchronous: `alembic check` drives env.py, which calls `asyncio.run()` itself and
    cannot be nested inside a running event loop.
    """
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    try:
        command.check(Config(str(alembic_ini)))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover -- only on a real drift
        pytest.fail(
            f"models and migrations have drifted; generate a migration:\n{exc}",
            pytrace=False,
        )


async def test_postgis_and_citext_are_available(engine: AsyncEngine) -> None:
    async with engine.connect() as conn:
        installed = set(
            (await conn.execute(text("select extname from pg_extension"))).scalars().all()
        )

    assert {"postgis", "citext"} <= installed


async def test_event_must_end_after_it_starts(engine: AsyncEngine) -> None:
    """Mirrors the domain's own requirement, enforced where no client can bypass it."""
    with pytest.raises(IntegrityError, match="ck_events_ends_after_arrival"):
        await _insert_event(engine, ends_at=ARRIVAL - timedelta(hours=1))


async def test_only_one_in_flight_job_per_event(engine: AsyncEngine) -> None:
    """The 409-on-concurrent-optimize contract, enforced by the database (docs/design.md 5.1).

    This is the assertion that keeps duplicate-job prevention out of application logic: two API
    instances racing cannot both insert, regardless of how the request handler is written.
    """
    event_id = await _insert_event(engine)
    await _insert_job(engine, event_id, "queued")

    with pytest.raises(IntegrityError, match="one_active_job_per_event"):
        await _insert_job(engine, event_id, "running")


async def test_a_finished_job_frees_the_slot(engine: AsyncEngine) -> None:
    """The index is partial for a reason: history must not block the next optimize."""
    event_id = await _insert_event(engine)
    await _insert_job(engine, event_id, "succeeded")
    await _insert_job(engine, event_id, "failed")
    await _insert_job(engine, event_id, "cancelled")

    await _insert_job(engine, event_id, "queued")


async def test_only_one_active_solution_per_event(engine: AsyncEngine) -> None:
    event_id = await _insert_event(engine)
    await _insert_job(engine, event_id, "queued")

    async def insert_solution(is_active: bool) -> None:
        async with engine.begin() as conn:
            job_id = (
                await conn.execute(
                    text("select id from optimization_jobs where event_id = :e limit 1"),
                    {"e": event_id},
                )
            ).scalar_one()
            await conn.execute(
                text(
                    "insert into solutions"
                    " (id, event_id, job_id, algorithm, objective_value, metrics,"
                    "  input_version, is_active)"
                    " values (:id, :event_id, :job_id, 'greedy', 1.0, '{}'::jsonb, 0, :is_active)"
                ),
                {
                    "id": uuid.uuid4(),
                    "event_id": event_id,
                    "job_id": job_id,
                    "is_active": is_active,
                },
            )

    await insert_solution(is_active=True)
    await insert_solution(is_active=False)
    await insert_solution(is_active=False)

    with pytest.raises(IntegrityError, match="one_active_solution_per_event"):
        await insert_solution(is_active=True)


async def test_seats_available_cannot_be_negative(engine: AsyncEngine) -> None:
    event_id = await _insert_event(engine)

    with pytest.raises(IntegrityError, match="seats_available_non_negative"):
        async with engine.begin() as conn:
            await conn.execute(
                text(
                    "insert into participants"
                    " (id, event_id, display_name, role, seats_available, pickup_address,"
                    "  token_hash)"
                    " values (:id, :event_id, 'Jane', 'driver', -1, '1 Main St', :token)"
                ),
                {"id": uuid.uuid4(), "event_id": event_id, "token": b"\x01"},
            )


async def test_participant_role_enum_matches_the_domain(engine: AsyncEngine) -> None:
    """`Role.EITHER` is dormant, not dead (CLAUDE.md) -- the column must still accept it.

    The database enum and `carpool_domain.Role` are declared separately, because a column
    definition must not import the domain (docs/design.md 4.1). This is what keeps them in step.
    """
    from carpool_domain.models import Role

    async with engine.connect() as conn:
        labels = set(
            (
                await conn.execute(
                    text(
                        "select e.enumlabel from pg_enum e"
                        " join pg_type t on t.oid = e.enumtypid"
                        " where t.typname = 'participant_role'"
                    )
                )
            )
            .scalars()
            .all()
        )

    assert labels == {role.value for role in Role}
    assert ParticipantRole.EITHER.value in labels
