/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Event
         * @description Create an event and mint its organizer token.
         *
         *     Status is `open` on creation: in Model A there is no submission window to wait for, so a `draft`
         *     state would be a step every organizer immediately skips.
         */
        post: operations["create_event_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_v1_events__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Event
         * @description Edit event details.
         *
         *     Permitted while the event is locked: locking freezes the *roster*, and a venue or time change is
         *     exactly the kind of correction an organizer needs to make after that point. An archived event is
         *     immutable.
         */
        patch: operations["patch_event_v1_events__public_id__patch"];
        trace?: never;
    };
    "/v1/events/{public_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock Event
         * @description Freeze the roster. Idempotent -- re-locking a locked event is a no-op, not an error, because
         *     a double-tapped button is not a conflict.
         */
        post: operations["lock_event_v1_events__public_id__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{public_id}/optimizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Optimization
         * @description Enqueue -- and, for now, immediately run -- an optimization.
         *
         *     `202` means a job was created. `200` means an existing one is being returned instead: an
         *     idempotent retry, or a fingerprint matching an instance already solved. The body is identical
         *     either way, so a client that polls `job_id` need not distinguish them.
         */
        post: operations["create_optimization_v1_events__public_id__optimizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{public_id}/optimizations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Optimization
         * @description Poll a job (docs/design.md 4.3 -- polling, not SSE, in v1).
         *
         *     Nested under the event rather than at the bare `/v1/optimizations/{job_id}` of docs/design.md 6:
         *     an organizer token is scoped to an event, so the path must name the event for the dependency to
         *     authorize it at all. A flat path would make the job id itself the credential.
         */
        get: operations["get_optimization_v1_events__public_id__optimizations__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Optimization
         * @description Request cancellation. Cooperative, by design (docs/design.md 6.3).
         *
         *     This sets `cancel_requested`; a worker checks it between solver iterations and exits cleanly.
         *     Killing a worker mid-transaction is not safe, and pretending a `DELETE` does it is a common
         *     mistake. A finished job is returned untouched: there is nothing left to stop, and rewriting its
         *     status would destroy the record of what happened.
         */
        delete: operations["cancel_optimization_v1_events__public_id__optimizations__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{public_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Participants
         * @description The active roster, in the order people were added.
         *
         *     Cancelled participants are omitted: they are not on the roster, do not count towards the cap and
         *     are not given to the solver. They remain readable individually, because a solution computed
         *     before someone dropped out still refers to them.
         */
        get: operations["list_participants_v1_events__public_id__participants_get"];
        put?: never;
        /**
         * Add Participant
         * @description Add someone to the roster.
         *
         *     A participant token is minted and stored as a digest, but deliberately **not returned**: no
         *     endpoint accepts one yet, so handing it out would be handing out a credential that does nothing.
         *     The column is not-null, and a digest nobody holds the preimage of is simply unusable until a
         *     reissue path exists alongside the participant endpoints (docs/design.md 6.1).
         */
        post: operations["add_participant_v1_events__public_id__participants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{public_id}/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Participant */
        get: operations["get_participant_v1_events__public_id__participants__participant_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Participant
         * @description Take someone off the roster.
         *
         *     A soft cancel: the row stays, `status` becomes `cancelled`, and the seat is returned to the cap.
         *     Idempotent -- cancelling an already-cancelled participant still answers 200, because the
         *     caller's intent is satisfied either way, but it does not bump the version: nothing changed.
         *
         *     Any pin *pointing at* this person is cleared, or the solver would be left holding a constraint
         *     naming a driver who is no longer coming.
         */
        delete: operations["cancel_participant_v1_events__public_id__participants__participant_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Participant
         * @description Edit on someone's behalf -- the organizer path for "my address changed, can you fix it".
         *
         *     No cap check: an edit cannot add an active participant, since reactivating a cancelled one is
         *     deliberately not offered here (re-adding them is a new snapshot, which is the honest record).
         */
        patch: operations["patch_participant_v1_events__public_id__participants__participant_id__patch"];
        trace?: never;
    };
    "/v1/events/{public_id}/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Solutions
         * @description Every solution for this event, newest first.
         *
         *     History is kept rather than overwritten: comparing this week's answer with last week's is how an
         *     organizer judges whether a re-optimization was worth the disruption (docs/design.md 8.4).
         */
        get: operations["list_solutions_v1_events__public_id__solutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{public_id}/solutions/{solution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solution */
        get: operations["get_solution_v1_events__public_id__solutions__solution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{public_id}/solutions/{solution_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Solution
         * @description Make this the event's live answer.
         *
         *     Deactivating the incumbent and activating this one happen in one transaction, so
         *     `one_active_solution_per_event` is never momentarily violated and no reader ever sees two live
         *     answers or none. Activating the already-active solution is a no-op rather than an error.
         *
         *     A stale solution can still be activated on purpose: the organizer may well prefer a known
         *     arrangement over re-solving an hour before the event. The response says it is stale; it does not
         *     refuse.
         */
        post: operations["activate_solution_v1_events__public_id__solutions__solution_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Destination
         * @description Where the event is. Latitude first, as in every payload this API accepts.
         */
        Destination: {
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * EventCreate
         * @description `extra="forbid"` throughout: a misspelled field is a bug, and silently ignoring it is worse
         *     than a 422 -- an event created with a mistyped `ends_at` looks like it worked.
         */
        EventCreate: {
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            destination: components["schemas"]["Destination"];
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            weights?: components["schemas"]["Weights"] | null;
        };
        /**
         * EventCreated
         * @description The one and only time the organizer token is visible.
         *
         *     Only its SHA-256 digest is stored, so a lost token cannot be recovered -- it can only be
         *     reissued. There is deliberately no `join_url` yet: minting a join token while no endpoint
         *     accepts one would hand the caller a link that silently does nothing (docs/roadmap.md, Week 2).
         */
        EventCreated: {
            event: components["schemas"]["EventOrganizerRead"];
            /** Organizer Token */
            organizer_token: string;
            /**
             * Organizer Token Expires At
             * Format: date-time
             */
            organizer_token_expires_at: string;
        };
        /**
         * EventOrganizerRead
         * @description The organizer's view of an event.
         *
         *     The participant and joiner views are separate classes, added with the join flow. This one is
         *     unredacted; being explicit about that is the point of having one model per audience.
         */
        EventOrganizerRead: {
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            destination: components["schemas"]["Destination"];
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Name */
            name: string;
            /** Participants Version */
            participants_version: number;
            /** Public Id */
            public_id: string;
            status: components["schemas"]["EventStatus"];
            /** Timezone */
            timezone: string;
            weights: components["schemas"]["Weights"];
        };
        /**
         * EventPatch
         * @description Every field optional; only those actually sent are applied (`exclude_unset`).
         *
         *     The destination moves as a unit -- an address without its coordinates would leave the two
         *     describing different places, and there is no geocoder yet to re-derive one from the other.
         *     That is why `destination` is a nested object here rather than three sibling fields.
         */
        EventPatch: {
            /** Arrival At */
            arrival_at?: string | null;
            destination?: components["schemas"]["Destination"] | null;
            /** Ends At */
            ends_at?: string | null;
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            weights?: components["schemas"]["Weights"] | null;
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "draft" | "open" | "locked" | "archived";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * JobConflict
         * @description The 409 body when a job is already in flight for this event.
         *
         *     Carries the existing job id so the client polls that one instead of retrying -- a retry would
         *     hit the same partial unique index and fail again (docs/design.md 5.1).
         */
        JobConflict: {
            /** Detail */
            detail: string;
            /** Existing Job Id */
            existing_job_id: string | null;
        };
        /**
         * JobRead
         * @description A job as the client polls it (docs/design.md 4.3 -- polling, not SSE, in v1).
         */
        JobRead: {
            /** Algorithm */
            algorithm: string;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Error */
            error: string | null;
            /** Event Public Id */
            event_public_id: string;
            /** Finished At */
            finished_at: string | null;
            /** Input Version */
            input_version: number;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Progress */
            progress: {
                [key: string]: unknown;
            } | null;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Solution Id */
            solution_id: string | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
            weights: components["schemas"]["Weights"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * LegRead
         * @description One leg of one car. The legs carry different orderings on purpose (docs/design.md 8.2).
         */
        LegRead: {
            leg: components["schemas"]["RouteLeg"];
            /** Stops */
            stops: components["schemas"]["StopRead"][];
        };
        /**
         * OptimizationCreate
         * @description What to solve and how.
         *
         *     No `preserve_previous` yet, though docs/design.md 6 lists one: it would set the churn weight
         *     against the previously activated solution, and greedy cannot steer by churn: it constructs
         *     from nothing. The flag arrives with LNS, whose acceptance criterion can actually honour it
         *     (docs/design.md 8.4). Offering it now would be a switch that silently does nothing.
         */
        OptimizationCreate: {
            /**
             * Algorithm
             * @default greedy
             * @constant
             */
            algorithm: "greedy";
            weights?: components["schemas"]["Weights"] | null;
        };
        /** ParticipantCreate */
        ParticipantCreate: {
            /** Display Name */
            display_name: string;
            /** Earliest Departure */
            earliest_departure?: string | null;
            /** Email */
            email?: string | null;
            /** Latest Arrival */
            latest_arrival?: string | null;
            /** Max Detour Minutes */
            max_detour_minutes?: number | null;
            /**
             * Needs Outbound
             * @default true
             */
            needs_outbound: boolean;
            /**
             * Needs Return
             * @default true
             */
            needs_return: boolean;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            pickup: components["schemas"]["Pickup"];
            /** Pinned Driver Id */
            pinned_driver_id?: string | null;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** @default passenger */
            role: components["schemas"]["ParticipantRole"];
            /**
             * Seats Available
             * @default 0
             */
            seats_available: number;
        };
        /**
         * ParticipantOrganizerRead
         * @description The organizer's view: everything, contact details and full address included.
         *
         *     Built field by field so that adding a column to `participants` cannot quietly add it to a
         *     response -- which on this table would mean leaking `token_hash` or a pickup point.
         */
        ParticipantOrganizerRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Earliest Departure */
            earliest_departure: string | null;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latest Arrival */
            latest_arrival: string | null;
            /** Max Detour Minutes */
            max_detour_minutes: number | null;
            /** Needs Outbound */
            needs_outbound: boolean;
            /** Needs Return */
            needs_return: boolean;
            /** Notes */
            notes: string | null;
            /** Phone */
            phone: string | null;
            pickup: components["schemas"]["PickupRead"];
            /** Pinned Driver Id */
            pinned_driver_id: string | null;
            /** Priority */
            priority: number;
            role: components["schemas"]["ParticipantRole"];
            /** Seats Available */
            seats_available: number;
            status: components["schemas"]["ParticipantStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ParticipantPatch
         * @description Every field optional. The pickup moves as a unit, as the event's destination does.
         */
        ParticipantPatch: {
            /** Display Name */
            display_name?: string | null;
            /** Earliest Departure */
            earliest_departure?: string | null;
            /** Email */
            email?: string | null;
            /** Latest Arrival */
            latest_arrival?: string | null;
            /** Max Detour Minutes */
            max_detour_minutes?: number | null;
            /** Needs Outbound */
            needs_outbound?: boolean | null;
            /** Needs Return */
            needs_return?: boolean | null;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            pickup?: components["schemas"]["Pickup"] | null;
            /** Pinned Driver Id */
            pinned_driver_id?: string | null;
            /** Priority */
            priority?: number | null;
            role?: components["schemas"]["ParticipantRole"] | null;
            /** Seats Available */
            seats_available?: number | null;
        };
        /**
         * ParticipantRole
         * @enum {string}
         */
        ParticipantRole: "driver" | "passenger" | "either";
        /**
         * ParticipantStatus
         * @enum {string}
         */
        ParticipantStatus: "active" | "cancelled";
        /**
         * ParticipantWritten
         * @description The result of any single roster mutation, with the version that mutation produced.
         */
        ParticipantWritten: {
            participant: components["schemas"]["ParticipantOrganizerRead"];
            /** Participants Version */
            participants_version: number;
        };
        /**
         * Pickup
         * @description Where this person is collected. Latitude first, as everywhere in this API.
         *
         *     Coordinates are required until the Week 4 geocoder can derive them from the address, at which
         *     point they become an optional override. They are stored on the participant row with
         *     `geocode_source = 'user'` -- provider-resolved coordinates go to the TTL'd cache instead, which
         *     is what keeps the choice of geocoder reversible (docs/design.md 5.2).
         */
        Pickup: {
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * PickupRead
         * @description Coordinates are nullable on the way out: from Week 4 a provider-geocoded participant has none
         *     of their own, and the solve-time cache supplies them.
         */
        PickupRead: {
            /** Address */
            address: string;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
        };
        /** Readiness */
        Readiness: {
            /**
             * Database
             * @enum {string}
             */
            database: "up" | "down";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /**
         * RosterRead
         * @description The active roster, with the version it was read at.
         *
         *     The version travels with the roster so a client can tell that a solution it is displaying was
         *     computed against an earlier one (docs/design.md 5.1).
         */
        RosterRead: {
            /** Participants */
            participants: components["schemas"]["ParticipantOrganizerRead"][];
            /** Participants Version */
            participants_version: number;
        };
        /**
         * RouteLeg
         * @enum {string}
         */
        RouteLeg: "outbound" | "return";
        /** RouteRead */
        RouteRead: {
            /** Detour Seconds */
            detour_seconds: number;
            /** Driver Name */
            driver_name: string;
            /**
             * Driver Participant Id
             * Format: uuid
             */
            driver_participant_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            inbound: components["schemas"]["LegRead"];
            outbound: components["schemas"]["LegRead"];
            /** Seats Used */
            seats_used: number;
            /** Total Distance M */
            total_distance_m: number;
            /** Total Duration S */
            total_duration_s: number;
        };
        /**
         * SolutionRead
         * @description A full solution, as the results screen needs it.
         */
        SolutionRead: {
            /** Algorithm */
            algorithm: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Version */
            input_version: number;
            /** Is Active */
            is_active: boolean;
            /** Is Stale */
            is_stale: boolean;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Objective Value */
            objective_value: number;
            /** Routes */
            routes: components["schemas"]["RouteRead"][];
            /** Unassigned */
            unassigned: components["schemas"]["UnassignedRead"][];
        };
        /**
         * SolutionSummary
         * @description One entry in the history list. Deliberately without routes -- an organizer comparing runs
         *     wants the shape of each answer, not every stop in all of them.
         */
        SolutionSummary: {
            /** Algorithm */
            algorithm: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Version */
            input_version: number;
            /** Is Active */
            is_active: boolean;
            /** Is Stale */
            is_stale: boolean;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Objective Value */
            objective_value: number;
        };
        /** StopRead */
        StopRead: {
            /** Display Name */
            display_name: string;
            /**
             * Eta
             * Format: date-time
             */
            eta: string;
            /**
             * Participant Id
             * Format: uuid
             */
            participant_id: string;
            /** Pickup Address */
            pickup_address: string;
            /** Seq */
            seq: number;
        };
        /** UnassignedRead */
        UnassignedRead: {
            /** Display Name */
            display_name: string;
            /**
             * Participant Id
             * Format: uuid
             */
            participant_id: string;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Weights
         * @description All non-negative: a negative weight would pay the objective to do the thing it names.
         *
         *     **All finite, too.** `json.loads` accepts the non-standard `Infinity` and `NaN` tokens, and a
         *     bare `float` field takes them, so `allow_inf_nan=False` is what keeps them out. It is not
         *     hypothetical tidiness: `inf` survived validation, reached `json.dumps`, and came back out as a
         *     bare `Infinity` token that PostgreSQL's JSONB rejects -- a 500 on an endpoint reachable without
         *     authentication. `inf * 0` would also make the objective `NaN` if one ever reached the solver.
         */
        Weights: {
            /**
             * Churn
             * @default 0
             */
            churn: number;
            /**
             * Drive Time
             * @default 1
             */
            drive_time: number;
            /**
             * Driver Detour
             * @default 1
             */
            driver_detour: number;
            /**
             * Passenger Ride Time
             * @default 0.5
             */
            passenger_ride_time: number;
            /**
             * Unassigned
             * @default 100000
             */
            unassigned: number;
            /**
             * Vehicle
             * @default 600
             */
            vehicle: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    create_event_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_v1_events__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOrganizerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_event_v1_events__public_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOrganizerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_event_v1_events__public_id__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOrganizerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_optimization_v1_events__public_id__optimizations_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OptimizationCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_optimization_v1_events__public_id__optimizations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_optimization_v1_events__public_id__optimizations__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_participants_v1_events__public_id__participants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_participant_v1_events__public_id__participants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantWritten"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participant_v1_events__public_id__participants__participant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOrganizerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_participant_v1_events__public_id__participants__participant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantWritten"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_participant_v1_events__public_id__participants__participant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantWritten"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_solutions_v1_events__public_id__solutions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_solution_v1_events__public_id__solutions__solution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solution_id: string;
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_solution_v1_events__public_id__solutions__solution_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solution_id: string;
                /** @description The event's public handle */
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
