"""core schema

The tables in docs/design.md 5. Autogenerated from the models, then corrected by hand for three
things autogenerate cannot see:

* **citext.** `events.organizer_email` and `participants.email` are case-insensitive text, so the
  extension has to exist before the tables that use it.
* **Enum types outlive their tables.** `create_table` creates a Postgres enum implicitly, but
  `drop_table` does not drop it, so a downgrade followed by an upgrade would fail with "type
  already exists". The downgrade drops each one explicitly.
* **The geoalchemy2 import**, which autogenerate references but does not add.

The two partial unique indexes are the load-bearing part of this migration. They are what makes
duplicate-job prevention and solution activation race-free in the database rather than in
application logic (docs/design.md 5.1).

Revision ID: 7cc54778661d
Revises: eca28f4b35ae
Create Date: 2026-09-14 19:24

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7cc54778661d"
down_revision: str | Sequence[str] | None = "eca28f4b35ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Created implicitly by create_table, dropped explicitly on the way down.
ENUM_TYPES = (
    "event_status",
    "token_kind",
    "job_status",
    "participant_role",
    "geocode_source",
    "precision_level",
    "participant_status",
    "route_leg",
)


def upgrade() -> None:
    op.execute("create extension if not exists citext")

    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("public_id", sa.Text(), nullable=False),
        sa.Column("organizer_user_id", sa.UUID(), nullable=True),
        sa.Column("organizer_email", postgresql.CITEXT(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("destination_address", sa.Text(), nullable=False),
        sa.Column(
            "destination_geog",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("arrival_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "open", "locked", "archived", name="event_status"),
            nullable=False,
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("template_event_id", sa.UUID(), nullable=True),
        sa.Column("participants_version", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > arrival_at", name=op.f("ck_events_ends_after_arrival")),
        sa.ForeignKeyConstraint(
            ["template_event_id"],
            ["events.id"],
            name=op.f("fk_events_template_event_id_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("public_id", name=op.f("uq_events_public_id")),
    )
    op.create_table(
        "geocode_cache",
        sa.Column("address_norm", sa.Text(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column(
            "cached_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("address_norm", name=op.f("pk_geocode_cache")),
    )
    op.create_table(
        "travel_cache",
        sa.Column("origin_cell", sa.BigInteger(), nullable=False),
        sa.Column("dest_cell", sa.BigInteger(), nullable=False),
        sa.Column("profile", sa.Text(), nullable=False),
        sa.Column("duration_s", sa.Integer(), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "origin_cell", "dest_cell", "profile", name=op.f("pk_travel_cache")
        ),
    )
    op.create_table(
        "event_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("organizer", "join", name="token_kind"), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_tokens_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_event_tokens_token_hash")),
    )
    op.create_table(
        "optimization_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "cancelled", name="job_status"),
            nullable=False,
        ),
        sa.Column("algorithm", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_fingerprint", sa.LargeBinary(), nullable=False),
        sa.Column("input_version", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_optimization_jobs_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_jobs")),
    )
    op.create_index(
        "jobs_claimable",
        "optimization_jobs",
        ["queued_at"],
        unique=False,
        postgresql_where=sa.text("status in ('queued', 'running')"),
    )
    # Two concurrent optimize requests cannot both create a job: one insert raises a unique
    # violation, which the API turns into 409 with the existing job id (docs/design.md 5.1).
    op.create_index(
        "one_active_job_per_event",
        "optimization_jobs",
        ["event_id"],
        unique=True,
        postgresql_where=sa.text("status in ('queued', 'running')"),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("driver", "passenger", "either", name="participant_role"),
            nullable=False,
        ),
        sa.Column("seats_available", sa.Integer(), server_default="0", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pinned_driver_id", sa.UUID(), nullable=True),
        sa.Column("needs_outbound", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("needs_return", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("pickup_address", sa.Text(), nullable=False),
        sa.Column(
            "pickup_geog",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "geocode_source",
            sa.Enum("provider", "user", name="geocode_source"),
            server_default="provider",
            nullable=False,
        ),
        sa.Column(
            "pickup_precision",
            sa.Enum("exact", "street", "neighborhood", name="precision_level"),
            server_default="exact",
            nullable=False,
        ),
        sa.Column("earliest_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_detour_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "cancelled", name="participant_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "seats_available >= 0",
            name=op.f("ck_participants_seats_available_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_participants_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pinned_driver_id"],
            ["participants.id"],
            name=op.f("fk_participants_pinned_driver_id_participants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_participants_token_hash")),
    )
    op.create_index(
        "ix_participants_event_id_active",
        "participants",
        ["event_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_participants_pickup_geog",
        "participants",
        ["pickup_geog"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "solutions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("algorithm", sa.Text(), nullable=False),
        sa.Column("objective_value", sa.Float(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_version", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_solutions_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["optimization_jobs.id"],
            name=op.f("fk_solutions_job_id_optimization_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_solutions")),
    )
    # Activation races cannot produce two live answers for one event.
    op.create_index(
        "one_active_solution_per_event",
        "solutions",
        ["event_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("solution_id", sa.UUID(), nullable=False),
        sa.Column("driver_participant_id", sa.UUID(), nullable=False),
        sa.Column("seats_used", sa.Integer(), nullable=False),
        sa.Column("total_distance_m", sa.Integer(), nullable=False),
        sa.Column("total_duration_s", sa.Integer(), nullable=False),
        sa.Column("detour_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "outbound_geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "return_geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["driver_participant_id"],
            ["participants.id"],
            name=op.f("fk_routes_driver_participant_id_participants"),
        ),
        sa.ForeignKeyConstraint(
            ["solution_id"],
            ["solutions.id"],
            name=op.f("fk_routes_solution_id_solutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routes")),
    )
    op.create_table(
        "unassigned_participants",
        sa.Column("solution_id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_unassigned_participants_participant_id_participants"),
        ),
        sa.ForeignKeyConstraint(
            ["solution_id"],
            ["solutions.id"],
            name=op.f("fk_unassigned_participants_solution_id_solutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "solution_id", "participant_id", name=op.f("pk_unassigned_participants")
        ),
    )
    op.create_table(
        "route_stops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("leg", sa.Enum("outbound", "return", name="route_leg"), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("eta", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_route_stops_participant_id_participants"),
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_route_stops_route_id_routes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_stops")),
        sa.UniqueConstraint("route_id", "leg", "seq", name="uq_route_stops_ordering"),
    )


def downgrade() -> None:
    op.drop_table("route_stops")
    op.drop_table("unassigned_participants")
    op.drop_table("routes")
    op.drop_index(
        "one_active_solution_per_event",
        table_name="solutions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("solutions")
    op.drop_index("ix_participants_pickup_geog", table_name="participants", postgresql_using="gist")
    op.drop_index(
        "ix_participants_event_id_active",
        table_name="participants",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("participants")
    op.drop_index(
        "one_active_job_per_event",
        table_name="optimization_jobs",
        postgresql_where=sa.text("status in ('queued', 'running')"),
    )
    op.drop_index(
        "jobs_claimable",
        table_name="optimization_jobs",
        postgresql_where=sa.text("status in ('queued', 'running')"),
    )
    op.drop_table("optimization_jobs")
    op.drop_table("event_tokens")
    op.drop_table("travel_cache")
    op.drop_table("geocode_cache")
    op.drop_table("events")

    # create_table creates these implicitly; drop_table does not remove them, and leaving them
    # behind makes a re-upgrade fail with "type already exists".
    for enum_name in ENUM_TYPES:
        op.execute(f"drop type if exists {enum_name}")

    # citext is left in place, like postgis in the baseline: dropping an extension would cascade
    # to anything still using it, and it is harmless when idle.
